chore: remove third party libraries from copyright

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -89,31 +89,6 @@ tasks:
       - adb push ./build/arduino-router_*_arm64.deb /tmp/
       - ./scripts/run-remote-sudo.sh "dpkg -i /tmp/arduino-router_*_arm64.deb && needrestart -r a"
 
-  update-deb-copyright:
-    desc: Extract project and dependency licenses into asd copyright
-    cmds:
-      - |
-          licensed notices
-
-          cat > debian/arduino-router/usr/share/doc/arduino-router/copyright <<EOF
-          Copyright 2025 ARDUINO SA (http://www.arduino.cc/)
-
-          This software is released under the GNU General Public License version 3,
-          which covers the main part of arduino-router.
-          The terms of this license can be found at:
-          https://www.gnu.org/licenses/gpl-3.0.en.html
-
-          You can be released from the requirements of the above licenses by purchasing
-          a commercial license. Buying such a license is mandatory if you want to
-          modify or otherwise use the software for commercial activities involving the
-          Arduino software without disclosing the source code of your own applications.
-          To purchase a commercial license, send an email to license@arduino.cc.
-
-          ---
-
-          EOF
-          cat .licenses/arduino-router/NOTICE  >> debian/arduino-router/usr/share/doc/arduino-router/copyright
-
   # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-dependencies-task/Taskfile.yml
   general:cache-dep-licenses:
     desc: Cache dependency license metadata
@@ -121,19 +96,19 @@ tasks:
       - task: general:prepare-deps
     cmds:
       - |
-          if
-            ! which licensed \
-            &>/dev/null
-          then
-            if [[ {{OS}} == "windows" ]]; then
-              echo "Licensed does not have Windows support."
-              echo "Please use Linux/macOS or download the dependencies cache from the GitHub Actions workflow artifact."
-            else
-              echo "licensed not found or not in PATH."
-              echo "Please install: https://github.com/licensee/licensed#installation"
-            fi
-            exit 1
+        if
+          ! which licensed \
+          &>/dev/null
+        then
+          if [[ {{OS}} == "windows" ]]; then
+            echo "Licensed does not have Windows support."
+            echo "Please use Linux/macOS or download the dependencies cache from the GitHub Actions workflow artifact."
+          else
+            echo "licensed not found or not in PATH."
+            echo "Please install: https://github.com/licensee/licensed#installation"
           fi
+          exit 1
+        fi
       - licensed cache
 
   # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-dependencies-task/Taskfile.yml
